services:
#  nginx:
#    image: nginx:alpine  # nginx 가벼운 버전
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf # nginx.conf파일을 컨테이너 안에 연결
#      - static_volume:/one_piece/static
#      - media_volume:/one_piece/media
#    networks:
#      - ws
#    depends_on:
#      - django


  django:
    container_name: django
    env_file:
      - envs/.env
    build:
      context: .
    image: ${DJANGO_IMAGE:-django}
    working_dir: /one_piece
    command: >
      sh -c "python manage.py migrate &&
             DJANGO_SETTINGS_MODULE=config.settings.prod python manage.py collectstatic --noinput &&
            sudo docker cp django:/one_piece/config/static/. ./static/ &&
             gunicorn -c gunicorn.conf.py config.wsgi:application "
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/one_piece/static
      - media_volume:/one_piece/media
    networks:
      - ws
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - envs/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_USER: postgres
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  ws:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data: