# Generated by Django 5.2.13 on 2026-04-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "s3_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("ai_categories", models.JSONField(blank=True, null=True)),
                ("ai_intensity", models.IntegerField(blank=True, null=True)),
                ("ai_keywords", models.JSONField(blank=True, null=True)),
                ("ai_comment", models.TextField(blank=True, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("is_helpful", models.BooleanField(default=False)),
                ("is_fallback", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "image_analysis",
            },
        ),
        migrations.CreateModel(
            name="ImageColorAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dominant_color_hex", models.JSONField(blank=True, null=True)),
                ("contrast_ratio", models.FloatField(blank=True, null=True)),
                ("avg_brightness", models.FloatField(blank=True, null=True)),
                ("avg_saturation", models.FloatField(blank=True, null=True)),
                ("is_failed", models.BooleanField(blank=True, default=False)),
                ("error_log", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "image_color_analysis",
            },
        ),
        migrations.CreateModel(
            name="Scent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("categories", models.JSONField(null=True)),
                ("intensity", models.IntegerField(null=True)),
                ("keywords", models.JSONField(null=True)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("scent_notes", models.JSONField(blank=True, null=True)),
                (
                    "thumbnail_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("season", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "scent",
            },
        ),
    ]
