# Generated by Django 5.2.13 on 2026-04-15 04:39

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("eng_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("categories", models.CharField(max_length=255)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20), blank=True, default=list, size=None
                    ),
                ),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20), blank=True, default=list, size=None
                    ),
                ),
                ("intensity", models.IntegerField()),
                ("is_bestseller", models.BooleanField(blank=True, null=True)),
                ("scent_notes", models.JSONField(blank=True, null=True)),
                ("profile", models.JSONField(blank=True, null=True)),
                (
                    "season",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), blank=True, null=True, size=None
                    ),
                ),
                ("recommended_places", models.JSONField(blank=True, default=list, null=True)),
                (
                    "similar_scents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, null=True, size=None
                    ),
                ),
                ("thumbnail_url", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "scent",
                "indexes": [
                    models.Index(fields=["is_bestseller"], name="scent_is_best_a49c37_idx"),
                    models.Index(fields=["season"], name="scent_season_4dde1a_idx"),
                    models.Index(fields=["categories"], name="scent_categor_f36dd3_idx"),
                    django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="scent_tags_gin"),
                    django.contrib.postgres.indexes.GinIndex(fields=["keywords"], name="scent_keywords_gin"),
                    django.contrib.postgres.indexes.GinIndex(fields=["scent_notes"], name="scent_notes_gin"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("s3_image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("ai_categories", models.JSONField(blank=True, null=True)),
                ("ai_intensity", models.IntegerField(blank=True, null=True)),
                ("ai_keywords", models.JSONField(blank=True, null=True)),
                ("ai_comment", models.TextField(blank=True, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("review", models.TextField(blank=True, max_length=300, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("is_helpful", models.BooleanField(default=False)),
                ("is_fallback", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "recommended_scent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="analysis.scent"),
                ),
            ],
            options={
                "db_table": "image_analysis",
            },
        ),
        migrations.CreateModel(
            name="ImageColorAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dominant_color_hex", models.JSONField(blank=True, null=True)),
                ("contrast_ratio", models.FloatField(blank=True, null=True)),
                ("avg_brightness", models.FloatField(blank=True, null=True)),
                ("avg_saturation", models.FloatField(blank=True, null=True)),
                ("is_failed", models.BooleanField(blank=True, default=False)),
                ("error_log", models.TextField(blank=True, null=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_metadata",
                        to="analysis.imageanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "image_color_analysis",
                "indexes": [models.Index(fields=["is_failed"], name="idx_is_failed")],
            },
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["-created_at"], name="idx_created_at"),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["user"], name="idx_user"),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["is_helpful"], name="idx_is_helpful"),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["is_fallback"], name="idx_is_fallback"),
        ),
    ]
