# Generated by Django 5.2.13 on 2026-04-13 02:51

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysis",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="imagecoloranalysis",
            name="analysis",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="analysis.imageanalysis"),
        ),
        migrations.AddIndex(
            model_name="scent",
            index=models.Index(fields=["is_bestseller"], name="scent_is_best_a49c37_idx"),
        ),
        migrations.AddIndex(
            model_name="scent",
            index=models.Index(fields=["season"], name="scent_season_4dde1a_idx"),
        ),
        migrations.AddIndex(
            model_name="scent",
            index=models.Index(fields=["categories"], name="scent_categor_f36dd3_idx"),
        ),
        migrations.AddIndex(
            model_name="scent",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="scent_tags_gin"),
        ),
        migrations.AddIndex(
            model_name="scent",
            index=django.contrib.postgres.indexes.GinIndex(fields=["keywords"], name="scent_keywords_gin"),
        ),
        migrations.AddIndex(
            model_name="scent",
            index=django.contrib.postgres.indexes.GinIndex(fields=["scent_notes"], name="scent_notes_gin"),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="recommended_scent",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="analysis.scent"),
        ),
        migrations.AddIndex(
            model_name="imagecoloranalysis",
            index=models.Index(fields=["is_failed"], name="idx_is_failed"),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["-created_at"], name="idx_created_at"),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["user"], name="idx_user"),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["is_helpful"], name="idx_is_helpful"),
        ),
        migrations.AddIndex(
            model_name="imageanalysis",
            index=models.Index(fields=["is_fallback"], name="idx_is_fallback"),
        ),
    ]
