# Generated by Django 5.2.13 on 2026-04-20 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_seed_scent_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imageanalysis",
            old_name="ai_categories",
            new_name="ai_tags",
        ),
    ]
