# Generated by Django 5.2.13 on 2026-04-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysis",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imagecoloranalysis",
            name="error_log",
            field=models.TextField(blank=True, null=True),
        ),
    ]
