# Generated by Django 5.2.13 on 2026-04-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_imageanalysis_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageanalysis",
            name="review",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="imagecoloranalysis",
            name="analysis",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="analysis.imageanalysis"),
        ),
    ]
