# Generated by Django 5.2.13 on 2026-04-22 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_rename_ai_categories_imageanalysis_ai_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_key", models.CharField(max_length=512, unique=True)),
                ("original_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_uploaded", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "image_resources",
            },
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="image_resource",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="analysis.imageresource",
            ),
            preserve_default=False,
        ),
    ]
