# Generated by Django 5.2.13 on 2026-04-15 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_alter_imageanalysis_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagecoloranalysis",
            name="analysis",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="image_metadata", to="analysis.imageanalysis"
            ),
        ),
    ]
