# Generated by Django 5.2.13 on 2026-04-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_imageresource_imageanalysis_image_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageanalysis",
            name="recommended_scent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="analysis.scent"
            ),
        ),
    ]
