# Generated by Django 5.2.13 on 2026-04-15 02:38

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_remove_scent_scent_tags_gin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scent",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="scent",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20), blank=True, default=list, size=None
            ),
        ),
        migrations.AddIndex(
            model_name="scent",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="scent_tags_gin"),
        ),
        migrations.AddIndex(
            model_name="scent",
            index=django.contrib.postgres.indexes.GinIndex(fields=["keywords"], name="scent_keywords_gin"),
        ),
    ]
