# Generated by Django 5.2.13 on 2026-04-10 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(max_length=255, unique=True, verbose_name="이메일"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=128, verbose_name="비밀번호"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("birthday", models.DateField(verbose_name="생년월일")),
                (
                    "social_type",
                    models.CharField(
                        choices=[("K", "Kakao"), ("N", "Naver"), ("G", "Google")],
                        default="GENERAL",
                        max_length=10,
                        verbose_name="가입 경로",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, unique=True, verbose_name="휴대전화"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=6,
                        verbose_name="성별",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ACTIVE",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("K", "Kakao"), ("N", "Naver"), ("G", "Google")],
                        max_length=20,
                        verbose_name="소셜 플랫폼",
                    ),
                ),
                ("social_id", models.CharField(max_length=255, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "소셜 연동 정보",
                "db_table": "social_user",
            },
        ),
        migrations.CreateModel(
            name="UserWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NO_LONGER_NEEDED", "더 이상 필요하지 않음"),
                            ("LACK_OF_INTEREST", "관심 부족"),
                            ("FOUND_BETTER_SERVICE", "더 나은 서비스 발견"),
                            ("PRIVACY_CONCERNS", "개인정보 보안 우려"),
                            ("POOR_SERVICE_QUALITY", "서비스 품질 불만족"),
                            ("TECHNICAL_ISSUES", "기술적 문제"),
                            ("LACK_OF_CONTENT", "콘텐츠 부족"),
                            ("OTHER", "기타"),
                        ],
                        max_length=30,
                        verbose_name="탈퇴 사유",
                    ),
                ),
                (
                    "other_reason",
                    models.TextField(blank=True, null=True, verbose_name="기타 사유"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="탈퇴 신청일"),
                ),
                (
                    "scheduled_delete_at",
                    models.DateTimeField(verbose_name="데이터 실제 삭제 예정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_withdrawal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "탈퇴 정보",
                "db_table": "user_withdrawal",
            },
        ),
    ]
