# Generated by Django 5.2.13 on 2026-04-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotrecommendation",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbotrecommendation",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
