# Generated by Django 5.2.13 on 2026-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0003_chatbotrecommendation_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotrecommendation",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
