# Generated by Django 5.2.13 on 2026-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_chatbotrecommendation_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotrecommendation",
            name="user_message",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
