# Generated by Django 5.2.13 on 2026-04-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=128, verbose_name="비밀번호"),
        ),
    ]
