# Generated by Django 5.2.13 on 2026-04-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
