# Generated by Django 5.2.13 on 2026-04-23 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_profile_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
