from typing import Any

# ========================
# 향수 데이터 30개
# ========================
SCENT_DATA: list[dict[str, Any]] = [
    {
        "id": 1,
        "name": "블라썸 드림",
        "englishName": "Blossom Dream",
        "category": "floral",
        "intensity": 76,
        "profile": {"freshness": 21, "warmth": 68, "softness": 48, "depth": 78, "sweetness": 82},
        "tags": ["따뜻한", "부드러운", "달콤한", "로맨틱"],
        "season": ["spring", "autumn"],
        "recommendedPlaces": ["Bedroom", "Dressing Room", "Living Room"],
        "isBestseller": True,
    },
    {
        "id": 2,
        "name": "로즈 미스트",
        "englishName": "Rose Mist",
        "category": "floral",
        "intensity": 64,
        "profile": {"freshness": 42, "warmth": 54, "softness": 72, "depth": 61, "sweetness": 46},
        "tags": ["우아한", "잔잔한", "플로럴", "정돈된"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Powder Room", "Bedroom", "Reading Room"],
        "isBestseller": False,
    },
    {
        "id": 3,
        "name": "화이트 피오니",
        "englishName": "White Peony",
        "category": "floral",
        "intensity": 58,
        "profile": {"freshness": 56, "warmth": 38, "softness": 74, "depth": 45, "sweetness": 41},
        "tags": ["맑은", "가벼운", "산뜻한", "깨끗한"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Entryway", "Living Room", "Powder Room"],
        "isBestseller": False,
    },
    {
        "id": 4,
        "name": "벨벳 블룸",
        "englishName": "Velvet Bloom",
        "category": "floral",
        "intensity": 73,
        "profile": {"freshness": 24, "warmth": 66, "softness": 70, "depth": 75, "sweetness": 57},
        "tags": ["우아한", "깊이감 있는", "풍부한", "성숙한"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Living Room", "Lounge", "Bedroom"],
        "isBestseller": True,
    },
    {
        "id": 5,
        "name": "체리 베일",
        "englishName": "Cherry Veil",
        "category": "floral",
        "intensity": 62,
        "profile": {"freshness": 47, "warmth": 42, "softness": 69, "depth": 53, "sweetness": 63},
        "tags": ["달콤한", "사랑스러운", "섬세한", "은은한"],
        "season": ["spring", "autumn"],
        "recommendedPlaces": ["Bedroom", "Vanity", "Reading Room"],
        "isBestseller": False,
    },
    {
        "id": 6,
        "name": "아이리스 페탈",
        "englishName": "Iris Petal",
        "category": "floral",
        "intensity": 59,
        "profile": {"freshness": 31, "warmth": 49, "softness": 80, "depth": 58, "sweetness": 32},
        "tags": ["차분한", "고급스러운", "부드러운", "정갈한"],
        "season": ["spring", "winter"],
        "recommendedPlaces": ["Study", "Bedroom", "Powder Room"],
        "isBestseller": False,
    },
    {
        "id": 7,
        "name": "세린 우즈",
        "englishName": "Serene Woods",
        "category": "woody",
        "intensity": 72,
        "profile": {"freshness": 28, "warmth": 86, "softness": 74, "depth": 88, "sweetness": 36},
        "tags": ["차분한", "깊이감 있는", "내추럴", "안정적인"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Study", "Reading Room", "Living Room"],
        "isBestseller": True,
    },
    {
        "id": 8,
        "name": "샌달 콰이어트",
        "englishName": "Sandal Quiet",
        "category": "woody",
        "intensity": 68,
        "profile": {"freshness": 18, "warmth": 84, "softness": 81, "depth": 79, "sweetness": 29},
        "tags": ["포근한", "부드러운", "차분한", "따뜻한"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Bedroom", "Living Room", "Lounge"],
        "isBestseller": True,
    },
    {
        "id": 9,
        "name": "시더 아워",
        "englishName": "Cedar Hour",
        "category": "woody",
        "intensity": 66,
        "profile": {"freshness": 33, "warmth": 72, "softness": 51, "depth": 80, "sweetness": 18},
        "tags": ["드라이한", "정돈된", "깊은", "고요한"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Study", "Office", "Entryway"],
        "isBestseller": False,
    },
    {
        "id": 10,
        "name": "앰버 우드",
        "englishName": "Amber Wood",
        "category": "woody",
        "intensity": 74,
        "profile": {"freshness": 17, "warmth": 88, "softness": 59, "depth": 85, "sweetness": 40},
        "tags": ["따뜻한", "묵직한", "고급스러운", "안정적인"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Living Room", "Lounge", "Bedroom"],
        "isBestseller": True,
    },
    {
        "id": 11,
        "name": "오크 리추얼",
        "englishName": "Oak Ritual",
        "category": "woody",
        "intensity": 79,
        "profile": {"freshness": 15, "warmth": 76, "softness": 43, "depth": 91, "sweetness": 14},
        "tags": ["묵직한", "깊은", "절제된", "집중되는"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Study", "Library", "Office"],
        "isBestseller": False,
    },
    {
        "id": 12,
        "name": "스모크드 팀버",
        "englishName": "Smoked Timber",
        "category": "woody",
        "intensity": 83,
        "profile": {"freshness": 12, "warmth": 79, "softness": 34, "depth": 94, "sweetness": 16},
        "tags": ["스모키한", "강렬한", "깊은", "묵직한"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Lounge", "Living Room", "Studio"],
        "isBestseller": False,
    },
    {
        "id": 13,
        "name": "시트러스 던",
        "englishName": "Citrus Dawn",
        "category": "citrus",
        "intensity": 57,
        "profile": {"freshness": 91, "warmth": 18, "softness": 36, "depth": 28, "sweetness": 34},
        "tags": ["상쾌한", "밝은", "가벼운", "깨끗한"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Kitchen", "Entryway", "Workspace"],
        "isBestseller": True,
    },
    {
        "id": 14,
        "name": "레몬 리넨",
        "englishName": "Lemon Linen",
        "category": "citrus",
        "intensity": 52,
        "profile": {"freshness": 88, "warmth": 16, "softness": 58, "depth": 24, "sweetness": 26},
        "tags": ["깨끗한", "가벼운", "산뜻한", "정돈된"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Laundry Room", "Bedroom", "Entryway"],
        "isBestseller": False,
    },
    {
        "id": 15,
        "name": "베르가못 에어",
        "englishName": "Bergamot Air",
        "category": "citrus",
        "intensity": 54,
        "profile": {"freshness": 86, "warmth": 22, "softness": 44, "depth": 31, "sweetness": 23},
        "tags": ["맑은", "산뜻한", "투명한", "가벼운"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Workspace", "Living Room", "Kitchen"],
        "isBestseller": False,
    },
    {
        "id": 16,
        "name": "그레이프프루트 글로우",
        "englishName": "Grapefruit Glow",
        "category": "citrus",
        "intensity": 56,
        "profile": {"freshness": 93, "warmth": 15, "softness": 29, "depth": 22, "sweetness": 31},
        "tags": ["경쾌한", "밝은", "상쾌한", "활기 있는"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Kitchen", "Home Gym", "Workspace"],
        "isBestseller": False,
    },
    {
        "id": 17,
        "name": "소프트 리넨",
        "englishName": "Soft Linen",
        "category": "musk",
        "intensity": 49,
        "profile": {"freshness": 63, "warmth": 41, "softness": 88, "depth": 36, "sweetness": 19},
        "tags": ["깨끗한", "포근한", "부드러운", "은은한"],
        "season": ["spring", "summer", "autumn"],
        "recommendedPlaces": ["Bedroom", "Laundry Room", "Living Room"],
        "isBestseller": True,
    },
    {
        "id": 18,
        "name": "코튼 베일",
        "englishName": "Cotton Veil",
        "category": "musk",
        "intensity": 44,
        "profile": {"freshness": 58, "warmth": 36, "softness": 91, "depth": 29, "sweetness": 17},
        "tags": ["은은한", "부드러운", "깨끗한", "가벼운"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Bedroom", "Nursery", "Powder Room"],
        "isBestseller": False,
    },
    {
        "id": 19,
        "name": "퓨어 허시",
        "englishName": "Pure Hush",
        "category": "musk",
        "intensity": 41,
        "profile": {"freshness": 54, "warmth": 33, "softness": 84, "depth": 32, "sweetness": 12},
        "tags": ["미니멀한", "깨끗한", "조용한", "절제된"],
        "season": ["spring", "summer", "autumn"],
        "recommendedPlaces": ["Minimal Living Room", "Bedroom", "Workspace"],
        "isBestseller": False,
    },
    {
        "id": 20,
        "name": "클린 베일",
        "englishName": "Clean Veil",
        "category": "musk",
        "intensity": 46,
        "profile": {"freshness": 67, "warmth": 29, "softness": 78, "depth": 27, "sweetness": 18},
        "tags": ["깨끗한", "데일리", "부드러운", "편안한"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Bathroom", "Bedroom", "Entryway"],
        "isBestseller": True,
    },
    {
        "id": 21,
        "name": "그린 포즈",
        "englishName": "Green Pause",
        "category": "green",
        "intensity": 61,
        "profile": {"freshness": 79, "warmth": 28, "softness": 46, "depth": 43, "sweetness": 17},
        "tags": ["싱그러운", "자연스러운", "환기되는", "편안한"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Living Room", "Sunroom", "Workspace"],
        "isBestseller": False,
    },
    {
        "id": 22,
        "name": "피그 가든",
        "englishName": "Fig Garden",
        "category": "green",
        "intensity": 67,
        "profile": {"freshness": 65, "warmth": 47, "softness": 62, "depth": 55, "sweetness": 28},
        "tags": ["싱그러운", "세련된", "내추럴", "여유로운"],
        "season": ["spring", "summer", "autumn"],
        "recommendedPlaces": ["Living Room", "Dining Room", "Sunroom"],
        "isBestseller": True,
    },
    {
        "id": 23,
        "name": "바질 셰이드",
        "englishName": "Basil Shade",
        "category": "green",
        "intensity": 63,
        "profile": {"freshness": 82, "warmth": 24, "softness": 34, "depth": 40, "sweetness": 12},
        "tags": ["허브한", "선명한", "환기되는", "드라이한"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Kitchen", "Workspace", "Dining Room"],
        "isBestseller": False,
    },
    {
        "id": 24,
        "name": "소프트 파우더",
        "englishName": "Soft Powder",
        "category": "powdery",
        "intensity": 51,
        "profile": {"freshness": 22, "warmth": 52, "softness": 92, "depth": 44, "sweetness": 27},
        "tags": ["포근한", "파우더리", "부드러운", "조용한"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Bedroom", "Vanity", "Powder Room"],
        "isBestseller": False,
    },
    {
        "id": 25,
        "name": "캐시미어 더스트",
        "englishName": "Cashmere Dust",
        "category": "powdery",
        "intensity": 57,
        "profile": {"freshness": 18, "warmth": 66, "softness": 89, "depth": 52, "sweetness": 33},
        "tags": ["포근한", "따뜻한", "부드러운", "아늑한"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Bedroom", "Living Room", "Reading Room"],
        "isBestseller": True,
    },
    {
        "id": 26,
        "name": "핑크 페퍼 데이",
        "englishName": "Pink Pepper Day",
        "category": "spicy",
        "intensity": 65,
        "profile": {"freshness": 48, "warmth": 57, "softness": 33, "depth": 49, "sweetness": 21},
        "tags": ["활기 있는", "개성 있는", "스파이시한", "선명한"],
        "season": ["spring", "autumn"],
        "recommendedPlaces": ["Studio", "Workspace", "Entryway"],
        "isBestseller": False,
    },
    {
        "id": 27,
        "name": "스파이스 베일",
        "englishName": "Spice Veil",
        "category": "spicy",
        "intensity": 77,
        "profile": {"freshness": 16, "warmth": 83, "softness": 38, "depth": 81, "sweetness": 27},
        "tags": ["이국적인", "따뜻한", "강렬한", "특별한"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Lounge", "Dining Room", "Living Room"],
        "isBestseller": False,
    },
    {
        "id": 28,
        "name": "오션 브레스",
        "englishName": "Ocean Breath",
        "category": "aquatic",
        "intensity": 53,
        "profile": {"freshness": 89, "warmth": 12, "softness": 35, "depth": 26, "sweetness": 14},
        "tags": ["청량한", "시원한", "넓은", "가벼운"],
        "season": ["summer"],
        "recommendedPlaces": ["Bathroom", "Living Room", "Entryway"],
        "isBestseller": False,
    },
    {
        "id": 29,
        "name": "페어 벨벳",
        "englishName": "Pear Velvet",
        "category": "fruity",
        "intensity": 60,
        "profile": {"freshness": 61, "warmth": 34, "softness": 66, "depth": 39, "sweetness": 58},
        "tags": ["사랑스러운", "밝은", "과즙감 있는", "부드러운"],
        "season": ["spring", "summer"],
        "recommendedPlaces": ["Bedroom", "Living Room", "Vanity"],
        "isBestseller": False,
    },
    {
        "id": 30,
        "name": "골든 앰버",
        "englishName": "Golden Amber",
        "category": "amber",
        "intensity": 78,
        "profile": {"freshness": 14, "warmth": 92, "softness": 61, "depth": 86, "sweetness": 45},
        "tags": ["따뜻한", "고급스러운", "깊은", "포근한"],
        "season": ["autumn", "winter"],
        "recommendedPlaces": ["Living Room", "Lounge", "Bedroom"],
        "isBestseller": True,
    },
]

# ========================
# 베스트셀러 ID 목록
# ========================
BESTSELLER_IDS: list[int] = [scent["id"] for scent in SCENT_DATA if scent["isBestseller"]]

# ========================
# 컨텍스트 → 향수 데이터 매핑 테이블
# ========================

# space 매핑
SPACE_TO_PLACE: dict[str, list[str]] = {
    "bedroom": ["Bedroom", "Dressing Room", "Vanity", "Nursery"],
    "livingroom": ["Living Room", "Lounge", "Sunroom", "Dining Room"],
    "bathroom": ["Bathroom", "Powder Room"],
    "study": ["Study", "Library", "Office", "Reading Room", "Workspace"],
    "kitchen": ["Kitchen", "Dining Room"],
    "office": ["Office", "Workspace", "Studio"],
    "entryway": ["Entryway"],
}

# mood 매핑
MOOD_TO_TAGS: dict[str, list[str]] = {
    "calm": ["차분한", "잔잔한", "고요한", "안정적인", "조용한", "정갈한"],
    "cozy": ["포근한", "따뜻한", "아늑한", "부드러운", "온기있는"],
    "fresh": ["상쾌한", "산뜻한", "청량한", "가벼운", "싱그러운", "맑은", "깨끗한", "투명한"],
    "romantic": ["로맨틱", "달콤한", "사랑스러운", "플로럴", "섬세한"],
    "focus": ["드라이한", "절제된", "집중되는", "정돈된", "미니멀한", "깊은"],
    "energetic": ["활기 있는", "경쾌한", "밝은", "선명한", "활기있는"],
    "luxury": ["고급스러운", "우아한", "깊이감 있는", "성숙한", "이국적인", "특별한"],
    "sweet": ["달콤한", "사랑스러운", "과즙감 있는", "섬세한"],
}
# mood → 선호 카테고리 매핑
MOOD_TO_CATEGORY: dict[str, list[str]] = {
    "calm": ["woody", "musk"],
    "cozy": ["woody", "powdery", "amber"],
    "fresh": ["citrus", "aquatic", "green"],
    "romantic": ["floral"],
    "focus": ["woody", "green"],
    "energetic": ["citrus", "spicy"],
    "luxury": ["woody", "amber", "floral"],
    "sweet": ["floral", "fruity"],
}

# mood → 프로필 기준 매핑
MOOD_TO_PROFILE: dict[str, dict[str, int]] = {
    "calm": {"warmth": 50, "softness": 60},
    "cozy": {"warmth": 65, "softness": 70},
    "fresh": {"freshness": 70},
    "romantic": {"sweetness": 50, "softness": 60},
    "focus": {"depth": 70},
    "energetic": {"freshness": 60},
    "luxury": {"depth": 75, "warmth": 60},
    "sweet": {"sweetness": 55},
}

# intensity 매핑 (intensity 수치 기준)
INTENSITY_RANGE: dict[str, tuple[int, int]] = {
    "light": (0, 60),
    "medium": (55, 75),
    "strong": (70, 100),
}

# time → 선호 season 매핑
TIME_TO_SEASON: dict[str, list[str]] = {
    "morning": ["spring", "summer"],
    "daytime": ["spring", "summer"],
    "evening": ["autumn", "winter"],
    "night": ["autumn", "winter"],
}

# time → 프로필 기준 매핑
TIME_TO_PROFILE: dict[str, dict[str, int]] = {
    "morning": {"freshness": 60},
    "daytime": {"freshness": 50},
    "evening": {"warmth": 60, "depth": 55},
    "night": {"warmth": 65, "softness": 65},
}
