# Generated by Django 5.2.13 on 2026-04-15 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analysis", "0005_alter_imagecoloranalysis_analysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.CharField(
                        choices=[("MO", "MOOD"), ("SP", "SPACE VIBE"), ("SC", "SCENT IMPRESSION")], max_length=2
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "키워드",
                "verbose_name_plural": "키워드 목록",
                "db_table": "keyword",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "질문",
                "verbose_name_plural": "질문 목록",
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="QuestionsAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer", models.CharField(max_length=10)),
                ("score", models.IntegerField(default=0)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="question.question")),
            ],
            options={
                "verbose_name": "답변 정보",
                "verbose_name_plural": "답변 목록",
                "db_table": "questions_answer",
                "indexes": [models.Index(fields=["question"], name="IDX_questions_question_id")],
            },
        ),
        migrations.CreateModel(
            name="QuestionsResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("division", models.CharField(choices=[("Q", "Question"), ("K", "Keyword")], max_length=2)),
                ("questions_json", models.JSONField()),
                ("answer_ai", models.CharField(max_length=20)),
                ("image_key", models.CharField(blank=True, max_length=30, null=True)),
                ("results_review", models.TextField(blank=True, null=True)),
                ("scent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="analysis.scent")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "질문 결과",
                "verbose_name_plural": "결과 목록",
                "db_table": "questions_results",
                "indexes": [
                    models.Index(fields=["user"], name="IDX_questions_results_user_id"),
                    models.Index(fields=["scent"], name="IDX_questions_results_scent_id"),
                ],
            },
        ),
    ]
