# Generated by Django 5.2.13 on 2026-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionsresults",
            name="answer_ai",
            field=models.TextField(),
        ),
    ]
