# Generated by Django 5.2.13 on 2026-04-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="questionsanswer",
            name="IDX_questions_questions_id",
        ),
        migrations.RemoveField(
            model_name="questionsanswer",
            name="question",
        ),
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="question.questionsanswer"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["answer"], name="IDX_questions_answer_id"),
        ),
    ]
