# Generated by Django 5.2.13 on 2026-04-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="score",
        ),
        migrations.AddField(
            model_name="questionsanswer",
            name="score",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
