# Generated by Django 5.2.13 on 2026-04-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0002_alter_questionsresults_answer_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="additional",
            field=models.TextField(blank=True, null=True),
        ),
    ]
