# Generated by Django 5.2.13 on 2026-04-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0003_remove_questionsanswer_idx_questions_questions_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="division",
            field=models.CharField(
                choices=[("MO", "MOOD"), ("SP", "SPACE VIBE"), ("SC", "SCENT IMPRESSION")], max_length=2
            ),
        ),
    ]
