# Generated by Django 5.2.13 on 2026-04-16 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0004_keyword_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionsanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="question.question"
            ),
        ),
    ]
