# Generated by Django 5.2.13 on 2026-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0005_alter_questionsanswer_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionsanswer",
            name="score",
        ),
        migrations.RemoveField(
            model_name="questionsresults",
            name="results_review",
        ),
        migrations.AddField(
            model_name="question",
            name="left_label",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="right_label",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionsresults",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionsresults",
            name="review",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="division",
            field=models.CharField(
                choices=[
                    ("MO", "MOOD"),
                    ("SN", "Scent Notes"),
                    ("TS", "Time & Season"),
                    ("PL", "Place"),
                    ("TE", "Texture"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.CharField(
                null=False,
                blank=False,
                max_length=30,
            ),
        ),
    ]
