# Generated by Django 5.2.13 on 2026-04-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0007_keyword_refresh_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="score",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("Dh", "depth"), ("Fs", "Freshness"), ("Wh", "warmth"), ("Ss", "softness")],
                default="",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionsanswer",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
