# Generated by Django 5.2.13 on 2026-04-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0009_keyword_refresh_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("Fs", "Freshness"), ("Dh", "depth"), ("Wh", "warmth"), ("Ss", "softness")], max_length=15
            ),
        ),
    ]
