# Generated by Django 5.2.13 on 2026-04-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0010_alter_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("Fs", "Freshness"), ("Ss", "softness"), ("Wh", "warmth"), ("Dh", "depth")], max_length=15
            ),
        ),
    ]
