# Generated by Django 5.2.13 on 2026-04-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0011_alter_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsresults",
            name="match_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("Fs", "Freshness"), ("Wh", "warmth"), ("Dh", "depth"), ("Ss", "softness")], max_length=15
            ),
        ),
    ]
