# Generated by Django 5.2.13 on 2026-04-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0012_questionsresults_match_score_alter_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("Ss", "softness"), ("Dh", "depth"), ("Wh", "warmth"), ("Fs", "Freshness")], max_length=15
            ),
        ),
    ]
