# Generated by Django 5.2.13 on 2026-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0014_alter_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsresults",
            name="is_helpful",
            field=models.BooleanField(default=False),
        ),
    ]
