# Generated by Django 5.2.13 on 2026-04-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0015_questionsresults_is_helpful"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("Fs", "freshness"), ("Ss", "softness"), ("Dh", "depth"), ("Wh", "warmth")], max_length=15
            ),
        ),
    ]
