# Generated by Django 5.2.13 on 2026-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0016_alter_question_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionsresults",
            name="division",
            field=models.CharField(choices=[("S", "survey"), ("K", "keyword")], max_length=2),
        ),
    ]
