# Generated by Django 5.2.13 on 2026-04-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("question", "0017_alter_questionsresults_division"),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("division", models.CharField()),
                ("result_id", models.CharField()),
                ("holding_time", models.CharField()),
                ("object_id", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "web_share list",
                "verbose_name_plural": "web_share list",
                "db_table": "share",
            },
        ),
    ]
