# Generated by Django 5.2.13 on 2026-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0018_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="holding_time",
            field=models.DateTimeField(),
        ),
    ]
