# Generated by Django 5.2.13 on 2026-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0019_alter_share_holding_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="image_url",
            field=models.CharField(default=""),
        ),
    ]
