name: Deploy

on:
  push:
    branches: [develop]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Docker 이미지 이름, 태그 자동생성해주는 도구 설정 (metadata-action)
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.local.yml"
          target: "~/app"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Docker 없으면 설치
            # Todo: 서버들어가서 envs/.env 설정하기
            if ! command -v docker &> /dev/null; then
              sudo apt update -y
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            else
              echo "Docker가 이미 설치되어 있습니다."
            fi
            
            cd ~/app

            # GitHub Container Registry 로그인
            echo ${{ secrets.GHCR_TOKEN }} | sudo docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

            # DJANGO_IMAGE를 env 파일에 저장
            DJANGO_IMAGE=ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest
            grep -q "^DJANGO_IMAGE=" envs/.env \
              && sed -i "s|^DJANGO_IMAGE=.*|DJANGO_IMAGE=$DJANGO_IMAGE|" envs/.env \
              || echo "DJANGO_IMAGE=$DJANGO_IMAGE" >> envs/.env

            # 최신 이미지 Pull & 재시작
            sudo docker compose -f docker-compose.local.yml --env-file envs/.env pull django
            sudo docker compose -f docker-compose.local.yml --env-file envs/.env up -d

            # 안 쓰는 이미지 정리
            sudo docker image prune -f