BLOCKED_PROMPT_KEYWORDS: list[str] = [
    "시스템 프롬프트",
    "system prompt",
    "developer message",
    "hidden prompt",
    "프롬프트 보여줘",
    "프롬프트 공개",
    "너의 지침",
    "너의 규칙",
    "규칙을 보여줘",
    "정책을 보여줘",
    "지시를 무시",
    "이전 지시 무시",
    "ignore instructions",
    "disregard",
    "override",
    "역할을 바꿔",
    "roleplay",
    "act as",
    "너는 이제",
    "탈옥",
    "jailbreak",
    "prompt injection",
    "api key",
    "secret key",
    "키를 알려줘",
    "temperature",
    "top_p",
    "system message",
    "gpt",
    "gemini",
    "claude",
    "llama",
    "openai",
    "모델 뭐야",
    "사용하는 모델",
]

BLOCKED_NONSENSE_KEYWORDS: list[str] = [
    "주식",
    "코인",
    "날씨",
    "야구",
    "축구",
    "농구",
    "번역해줘",
    "요약해줘",
    "코드 짜줘",
    "소설 써줘",
    "시 써줘",
    "대본 써줘",
    "광고 문구",
    "마케팅",
]

BLOCKED_PROFANITY_KEYWORDS: list[str] = [
    "씨발",
    "개새끼",
    "병신",
    "지랄",
    "ㅅㅂ",
    "ㅂㅅ",
]
