SPACE_MAPPING: dict[str, str] = {
    "침실": "bedroom",
    "방": "bedroom",
    "잠자리": "bedroom",
    "거실": "livingroom",
    "리빙룸": "livingroom",
    "욕실": "bathroom",
    "화장실": "bathroom",
    "서재": "study",
    "공부방": "study",
    "작업실": "study",
    "주방": "kitchen",
    "부엌": "kitchen",
    "사무실": "office",
    "회사": "office",
    "오피스": "office",
    "현관": "entryway",
}

MOOD_MAPPING: dict[str, str] = {
    "편안한": "calm",
    "차분한": "calm",
    "안정적인": "calm",
    "포근한": "cozy",
    "아늑한": "cozy",
    "따뜻한": "cozy",
    "상쾌한": "fresh",
    "청량한": "fresh",
    "시원한": "fresh",
    "산뜻한": "fresh",
    "싱그러운": "fresh",
    "로맨틱한": "romantic",
    "달콤한": "romantic",
    "사랑스러운": "romantic",
    "설레는": "romantic",
    "집중": "focus",
    "깔끔한": "focus",
    "절제된": "focus",
    "드라이한": "focus",
    "활기찬": "energetic",
    "생기있는": "energetic",
    "쌈뽕한": "energetic",
    "강렬한": "energetic",
    "경쾌한": "energetic",
    "고급스러운": "luxury",
    "우아한": "luxury",
    "깊은": "luxury",
    "묵직한": "luxury",
    "달달한": "sweet",
    "과즙": "sweet",
}

INTENSITY_MAPPING: dict[str, str] = {
    "진한": "strong",
    "강한": "strong",
    "쌈뽕한": "strong",
    "묵직한": "strong",
    "짙은": "strong",
    "은은한": "light",
    "가벼운": "light",
    "약한": "light",
    "살짝": "light",
    "적당한": "medium",
    "중간": "medium",
    "균형": "medium",
}

TIME_MAPPING: dict[str, str] = {
    "자기 전": "night",
    "잠들기 전": "night",
    "밤": "night",
    "저녁": "evening",
    "퇴근 후": "evening",
    "아침": "morning",
    "기상 후": "morning",
    "일어나서": "morning",
    "낮": "daytime",
    "오후": "daytime",
}
