SPACE_MAPPING: dict[str, str] = {
    # 집 전체
    "집": "livingroom",
    "집에서": "livingroom",
    "우리집": "livingroom",
    "자취방": "bedroom",
    "원룸": "bedroom",
    # 침실
    "침실": "bedroom",
    "방": "bedroom",
    "잠자리": "bedroom",
    "내방": "bedroom",
    "안방": "bedroom",
    "寝室": "bedroom",
    # 거실
    "거실": "livingroom",
    "리빙룸": "livingroom",
    "거실에서": "livingroom",
    "마루": "livingroom",
    # 욕실
    "욕실": "bathroom",
    "화장실": "bathroom",
    "욕조": "bathroom",
    "샤워실": "bathroom",
    "바스룸": "bathroom",
    # 서재
    "서재": "study",
    "공부방": "study",
    "작업실": "study",
    "독서실": "study",
    "공부": "study",
    "책상": "study",
    "독서": "study",
    # 주방
    "주방": "kitchen",
    "부엌": "kitchen",
    "주방에서": "kitchen",
    "요리": "kitchen",
    "식탁": "kitchen",
    "다이닝": "kitchen",
    # 사무실
    "사무실": "office",
    "회사": "office",
    "오피스": "office",
    "직장": "office",
    "업무": "office",
    "사무공간": "office",
    "재택": "office",
    "홈오피스": "office",
    # 현관
    "현관": "entryway",
    "입구": "entryway",
    "현관문": "entryway",
    "들어오면": "entryway",
    # 외출/야외 추가
    "밖에서": "office",
    "외출용": "office",
    "외출": "office",
    "야외": "entryway",
    "밖": "entryway",
    "나들이": "entryway",
    "데이트": "entryway",
    "외부": "office",
    "회사밖": "entryway",
}

MOOD_MAPPING: dict[str, str] = {
    # calm
    "편안한": "calm",
    "편안하게": "calm",
    "차분한": "calm",
    "차분하게": "calm",
    "안정적인": "calm",
    "조용한": "calm",
    "고요한": "calm",
    "잔잔한": "calm",
    "평온한": "calm",
    "릴렉스": "calm",
    "릴렉싱": "calm",
    "쉬고싶": "calm",
    "휴식": "calm",
    "안정": "calm",
    # cozy
    "포근한": "cozy",
    "포근하게": "cozy",
    "아늑한": "cozy",
    "아늑하게": "cozy",
    "따뜻한": "cozy",
    "따뜻하게": "cozy",
    "온기": "cozy",
    "푸근한": "cozy",
    "안락한": "cozy",
    # fresh
    "상쾌한": "fresh",
    "상쾌하게": "fresh",
    "청량한": "fresh",
    "청량하게": "fresh",
    "시원한": "fresh",
    "시원하게": "fresh",
    "산뜻한": "fresh",
    "산뜻하게": "fresh",
    "싱그러운": "fresh",
    "싱그럽게": "fresh",
    "맑은": "fresh",
    "깨끗한": "fresh",
    "상큼한": "fresh",
    "리프레시": "fresh",
    "리프레쉬": "fresh",
    "환기": "fresh",
    # romantic
    "로맨틱한": "romantic",
    "로맨틱하게": "romantic",
    "달콤한": "romantic",
    "사랑스러운": "romantic",
    "설레는": "romantic",
    "설레게": "romantic",
    "두근": "romantic",
    "플로럴": "romantic",
    "꽃향기": "romantic",
    "데이트": "romantic",
    "감성적인": "romantic",
    # focus
    "집중": "focus",
    "집중되는": "focus",
    "집중력": "focus",
    "깔끔한": "focus",
    "절제된": "focus",
    "드라이한": "focus",
    "정돈된": "focus",
    "스터디": "focus",
    "공부할때": "focus",
    "업무": "focus",
    "작업": "focus",
    "심플한": "focus",
    "미니멀": "focus",
    # energetic
    "활기찬": "energetic",
    "활기차게": "energetic",
    "생기있는": "energetic",
    "밝은": "energetic",
    "밝게": "energetic",
    "경쾌한": "energetic",
    "경쾌하게": "energetic",
    "활발한": "energetic",
    "에너지": "energetic",
    "상큼": "energetic",
    "비타민": "energetic",
    "기분전환": "energetic",
    "기분좋은": "energetic",
    "신나는": "energetic",
    # luxury
    "고급스러운": "luxury",
    "고급스럽게": "luxury",
    "우아한": "luxury",
    "우아하게": "luxury",
    "깊은": "luxury",
    "묵직한": "luxury",
    "성숙한": "luxury",
    "특별한": "luxury",
    "럭셔리": "luxury",
    "프리미엄": "luxury",
    "세련된": "luxury",
    # sweet
    "달달한": "sweet",
    "과즙": "sweet",
    "과일향": "sweet",
    "디저트": "sweet",
    "바닐라": "sweet",
    "캐러멜": "sweet",
    "초콜릿": "sweet",
}

INTENSITY_MAPPING: dict[str, str] = {
    # strong
    "진한": "strong",
    "강한": "strong",
    "강렬한": "strong",
    "묵직한": "strong",
    "짙은": "strong",
    "풍부한": "strong",
    "분명한": "strong",
    "확실한": "strong",
    "존재감있는": "strong",
    "강하게": "strong",
    # light
    "은은한": "light",
    "가벼운": "light",
    "약한": "light",
    "살짝": "light",
    "은은하게": "light",
    "가볍게": "light",
    "잔잔하게": "light",
    "연한": "light",
    "은은히": "light",
    "부드럽게": "light",
    # medium
    "적당한": "medium",
    "중간": "medium",
    "균형": "medium",
    "보통": "medium",
    "적절한": "medium",
    "딱맞는": "medium",
}

TIME_MAPPING: dict[str, str] = {
    # night
    "자기 전": "night",
    "잠들기 전": "night",
    "밤": "night",
    "밤에": "night",
    "취침": "night",
    "자기전": "night",
    "잠자기전": "night",
    "야간": "night",
    "심야": "night",
    # evening
    "저녁": "evening",
    "저녁에": "evening",
    "퇴근 후": "evening",
    "퇴근후": "evening",
    "저녁시간": "evening",
    "해질녘": "evening",
    "황혼": "evening",
    "노을": "evening",
    # morning
    "아침": "morning",
    "아침에": "morning",
    "기상 후": "morning",
    "기상후": "morning",
    "일어나서": "morning",
    "일어나면": "morning",
    "모닝": "morning",
    "기상": "morning",
    "새벽": "morning",
    # daytime
    "낮": "daytime",
    "낮에": "daytime",
    "오후": "daytime",
    "오전": "daytime",
    "점심": "daytime",
    "한낮": "daytime",
    "오후에": "daytime",
}

IMPATIENT_KEYWORDS: list[str] = [
    "아무거나",
    "그냥",
    "빨리",
    "뭐든",
    "상관없어",
    "상관없음",
    "아무거",
    "뭐라도",
    "대충",
    "그냥추천",
    "빠르게",
    "추천해줘",
    "추천해주세요",
    "걍",
    "바로",
    "빨리추천",
    "뭐든지",
    "아무꺼나",
    "골라줘",
    "정해줘",
]
